version: 2.1
  
orbs:
  node: circleci/node@5.0.2
  
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - /alpha-*/
                - /beta-*/
      - build:
          requires:
            - test
          filters:
            branches:
              ignore:
                - master
                - /alpha-*/
                - /beta-*/
  deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - /alpha-*/
                - /beta-*/
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - /alpha-*/
                - /beta-*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /alpha-*/
                - /beta-*/

jobs:
  test:
    working_directory: ~/repo
    executor:
      name: node/default
      tag: '16.12'
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn build:tokens
      - run: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    working_directory: ~/repo
    executor:
      name: node/default
      tag: '16.12'
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build packages
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    working_directory: ~/repo
    executor:
      name: node/default
      tag: '16.12'
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm run release
