name: Package Request
description: Create a package request 
labels: 'template: story'
title: "[Package]: "
labels: ["package", "triage"]
assignees:
  - The-Code-Monkey
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a package request! Please fill out this form as completely as possible.
  - type: input
    attributes:
      label: Package Name
      description: The name of the package
    validations:
      required: true
  - type: input
    attributes:
      label: Package Link
      description: A direct link to either the npm page or the github source.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
