name: Check bundle size

# This workflow only supported on pull requests
on: pull_request

jobs:
  # This workflow contains a single job called "size"
  size-limit:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      # The size limit github action
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}